// Minimal pagination shim — the kit's search.ejs.t expects PaginationSchema + Page<T>
// from this path. This is the smallest version that compiles + matches the import
// surface generated by the kit.

import { z } from 'zod';

export const PaginationSchema = z.object({
  limit: z.coerce.number().int().min(1).max(200).default(25),
  offset: z.coerce.number().int().min(0).default(0),
});

export type PaginationParams = z.infer<typeof PaginationSchema>;

export interface Page<T> {
  items: T[];
  limit: number;
  offset: number;
  total: number;
  has_more?: boolean;
}

export function paginated<T>(items: T[], total: number, params: PaginationParams): Page<T> {
  return {
    items,
    limit: params.limit,
    offset: params.offset,
    total,
    has_more: params.offset + items.length < total,
  };
}
