/**
 * Email module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { EmailsModule } from './emails.module';
export { EmailService } from './email.service';
export { EmailController } from './email.controller';

// Type-only exports (entity, DTOs)
export type { Email } from './email.entity';
export type { CreateEmailDto } from './dto/create-email.dto';
export type { UpdateEmailDto } from './dto/update-email.dto';
export type { EmailOutputDto } from './dto/email-output.dto';
