/**
 * Contact module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { ContactsModule } from './contacts.module';
export { ContactService } from './contact.service';
export { ContactController } from './contact.controller';

// Type-only exports (entity, DTOs)
export type { Contact } from './contact.entity';
export type { CreateContactDto } from './dto/create-contact.dto';
export type { UpdateContactDto } from './dto/update-contact.dto';
export type { ContactOutputDto } from './dto/contact-output.dto';
