/**
 * Opportunity module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { OpportunitiesModule } from './opportunities.module';
export { OpportunityService } from './opportunity.service';
export { OpportunityController } from './opportunity.controller';

// Type-only exports (entity, DTOs)
export type { Opportunity } from './opportunity.entity';
export type { CreateOpportunityDto } from './dto/create-opportunity.dto';
export type { UpdateOpportunityDto } from './dto/update-opportunity.dto';
export type { OpportunityOutputDto } from './dto/opportunity-output.dto';
